version: "3"
services:
  duty-designator:
    build: .
    ports:
      - "8080:8080"
  mongodb:
    image: mongo:latest
    volumes:
      - dutydb-data:/data/db
    ports:
      - "27017:27017"

volumes:
    dutydb-data:
