version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.7
      - image: mongo:latest
    working_directory: /go/src/duty-designator
    steps:
      - checkout
      - run: cd server; dep ensure
      - run: go test ./server/test
      - run: cd client; yarn;
orbs:
  node: circleci/node@1.1.6

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
