version: 2.1
jobs:
  build:
    docker:
      - image: openjdk:8-jdk
        user: root
      - image: mongo:latest
    working_directory: /go/src/duty-designator
    steps:
      - checkout
      - run: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      - run: echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
      - run: apt-get update
      - run: |
          apt-get install -y dbus-x11 google-chrome-stable libgtk2.0-0 \
          libnotify-dev \
          libgconf-2-4 \
          libnss3 \
          libxss1 \
          libasound2 \
          xvfb \
          gcc \
          libxml2-utils
      - run: rm -rf /var/lib/apt/lists/*
      - restore_cache:
          keys:
            - cache-{{ arch }}-{{ .Branch }}-{{ checksum "./e2e/package.json" }}
      - restore_cache:
          keys:
            - cache-4-{{ arch }}-{{ .Branch }}-{{ checksum "./server/gogradle.lock" }}
      - run: ./gradlew :server:goVendor
      - save_cache:
          key: cache-4-{{ arch }}-{{ .Branch }}-{{ checksum "./server/gogradle.lock" }}
          paths:
            - ./server/vendor
            - ./server/.gogradle
            - /root/.gradle
      - run: ./gradlew check
      - save_cache:
          key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "./e2e/package.json" }}
          paths:
            - ~/.cache
      - run: |
          mkdir artifacts
          mkdir artifacts/serverReports
          mkdir artifacts/e2e
          mkdir artifacts/e2e/screenshots
          mkdir artifacts/e2e/videos
          cp -r /go/src/duty-designator/server/.gogradle/reports artifacts/serverReports/
          cp -r e2e/videos artifacts/e2e/
          cp -r e2e/screenshots artifacts/e2e/
      - run: |
          mkdir results
          mkdir results/client
          mkdir results/e2e
          cp -r client/test-reports results/client
          cp -r e2e/results results/e2e
      - store_artifacts:
          path: artifacts
      - store_test_results:
          path: results
workflows:
  version: 2
  build_and_test:
    jobs:
      - build